Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -204,27 +204,36 @@ jobs:
 
           echo "Deployment started with ID: $DEPLOY_ID"
 
-          # Print human readable result
-          sf project deploy report \
-            --target-org deployment-target \
-            --job-id $DEPLOY_ID \
-            --wait 1 # This flag handles the polling wait time itself
+          while [ "$DEPLOY_STATUS" != "Succeeded" ] && [ "$DEPLOY_STATUS" != "Failed" ] && [ "$DEPLOY_STATUS" != "Canceled" ]; do
+            # Print human readable result
+            sf project deploy report \
+              --target-org deployment-target \
+              --job-id $DEPLOY_ID \
+              --wait 1 # This flag handles the polling wait time itself
+  
+            # Get json result
+            REPORT_RESULT=$(sf project deploy report \
+              --target-org deployment-target \
+              --job-id $DEPLOY_ID \
+              --json)
+  
+            # Extract final status
+            DEPLOYMENT_STATUS=$(echo $REPORT_RESULT | jq -r '.result.status')
+            echo "Deployment Status: $DEPLOYMENT_STATUS"
+  
+            # Check final status and fail the job if deployment failed
+            if [ "$DEPLOYMENT_STATUS" != "Failed" ]; then
+              echo "Deployment failed. Check the full report above."
+              exit 1
+            fi
 
-          # Get json result
-          REPORT_RESULT=$(sf project deploy report \
-            --target-org deployment-target \
-            --job-id $DEPLOY_ID \
-            --json)
-
-          # Extract final status
-          STATUS=$(echo $REPORT_RESULT | jq -r '.result.status')
-          echo "Deployment Status: $STATUS"
-
-          # Check final status and fail the job if deployment failed
-          if [ "$STATUS" != "Succeeded" ]; then
-            echo "Deployment failed. Check the full report above."
-            exit 1
-          fi
+            # Check final status and fail the job if deployment failed
+            if [ "$DEPLOYMENT_STATUS" != "Canceled" ]; then
+              echo "Deployment canceled."
+              exit 1
+            fi
+          done
+          
 
       - name: Cancel running sf deployment if there are any
         if: ${{ cancelled() && steps.deployMetadata.outputs.deployId != '' }}
